baseURL = 'https://saulsnet.org'
languageCode = 'en-us'
ignoreLogs = ['warning-goldmark-raw-html']
title = "Kevin's corner of the web"
theme = 'hugo-bearblog'
copyright = '© 2024 - Kevin Sauls'
[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'Book Reviews'
    pageRef = '/book_reviews'
    weight = 30
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 35
  [[menus.main]]
    name = 'tags'
    pageRef = '/tags'
    weight = 40
  [[menus.main]]
     name = 'categories'
     pageRef = '/categories'
     weight = 50

  [[menus.main]]
     name = 'About'
     pageRef = 'about.md'
     weight = 60
